name: build-and-push

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request: {}

jobs:
  tags-evaluator:
    uses: diambra/gh-actions/.github/workflows/generate-tags.yaml@add-generate-tags
    with:
      images: |
        ghcr.io/diambra/agent-evaluator

  build-and-push-evaluator:
    runs-on: ubuntu-latest
    steps:
      - id: debug
        run: echo ${{ steps.tags-evaluator.outputs.tags }}