name: build-and-push

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request: {}

jobs:
  build-and-push-evaluator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: diambra-bot # We need to pull the assets repo
          password: ${{ secrets.DIAMBRA_BOT_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - id: tags-evaluator
        uses: diambra/gh-actions/.github/workflows/generate-tags.yaml@add-generate-tags
        with:
          images: |
            ghcr.io/diambra/agent-evaluator
      - id: debug
        run: echo ${{ steps.tags-evaluator.outputs.tags }}